### PR TITLE
Add integrated testing

### PR DESCRIPTION
**Pull request by nocarryr**
The config and build steps are currently in place and through the creation of a "dummy" subclass of RtlSdr, the most basic tests are now passing in Python 2.7, 3.4 and 3.5:

https://travis-ci.org/nocarryr/pyrtlsdr/builds/109067044

I'd still like to reorganize tests and tidy things up, but I thought it would be a good time to share the current status

### CODE REVIEW

**Comment by nocarryr** [comment]
So this PR ended up with a few bugfixes that weren't intended to be included.  I suppose that's the whole point of testing (especially automated across multiple environments) so it's already shown its merits.

@roger- after a bit of cleanup, are you good with merging?  I can help with setting up the integration with travis-ci so that all future pushes and PR's go through testing automatically.

**Comment by nocarryr** [comment]
@roger- I'll take that as a +1, I'm gonna go ahead and merge

**Comment by roger-** [comment]
@nocarryr: sorry for the delay, just catching up on everything now. Looks good to me, will probably steal this code for another project haha. Thanks!

**Comment by nocarryr** [comment]
@roger- No problem.  Glad I could help!  Do you need any help with integrating this repo with [travis-ci](https://travis-ci.org)?

**Comment by roger-** [comment]
I'm pretty clueless about travis-ci, so I'm not sure what there next step would be -- so sure.

BTW is there a cleaner way to integrate this without direct modifications like [this](https://github.com/roger-/pyrtlsdr/blob/master/rtlsdr/rtlsdraio.py#L5)? I feel like it should be possiblet o keep the testing a bit more compartmentalized.

**Comment by nocarryr** [comment]
I was trying to figure out a way around that, but couldn't come up with anything that would be reliable and wouldn't require a whole lot of hack-ish code.

Do you think putting the CI environment check/override stuff at the lowest level possible would be better?  Possibly in the wrapper script itself?

**Comment by nocarryr** [comment]
As for the travis stuff, it's pretty simple.  Sign up on their site through your gh account and you should see all of your repositories show up in your profile page(I think it takes a few minutes for it to all get synced)

Then just hit the toggle thing to enable builds for rtlsdr.  It won't do anything until something triggers it so something will have to be commited and pushed.

Then you can watch the build sit there for 10 minutes or so while they install the deps and compile librtlsdr... THEN you'll see about 30 seconds of testing! lol

**Comment by roger-** [comment]
> Do you think putting the CI environment check/override stuff at the lowest level possible would be better? 

Actually I think keeping it at a higher level would be better. I'll have to give this some thought.

**Comment by roger-** [comment]
> Then just hit the toggle thing to enable builds for rtlsdr

Is that what you did [here](https://travis-ci.org/nocarryr/pyrtlsdr)?

**Comment by nocarryr** [comment]
Yup.  It doesn't show the total time though.  Since the build script uses `sudo` it takes a lot longer for the instances to spool up.  I've been meaning to try without sudo, but haven't checked yet if libusb is available on their package 'whitelist'.  Also, not sure if `ldconfig` is absolutely necessary in that environment.

**Comment by nocarryr** [comment]
Actually, I've got a commit candidate (or a PR if you want to see how cool that feature is) ready to go if you want to test things out.  It's related to the setup script modifications

**Comment by roger-** [comment]
Sure, I can take a look.

**Comment by nocarryr** [comment]
Did you set it up in travis yet?  Was going to wait on that

**Comment by roger-** [comment]
Yup, seems to be all set!

**Comment by nocarryr** [comment]
Alright.  Waiting on the push to my fork to finish its test then I'll open a PR

**Comment by nocarryr** [comment]
:+1:  looks like it's all set up properly

**Pull request merged**
