### PR TITLE
Make tcp client able to work without importing the wrapper

### PR DESCRIPTION
**Pull request by nocarryr**
See #44

### CODE REVIEW

**Comment by nocarryr** [comment]
Stupid test case discovery junk :rage:

**Comment by nocarryr** [comment]
@chibill what do you think of the solution?  I've not looked into all of the use cases yet, but is setting an environment variable something that can be done in yours?

**Comment by chibill** [comment]
I will take a look at it after work.

**Comment by chibill** [comment]
I can set environmental variables just fine.  And you may want it to warn on start that it's in client mode. So if people do forget it they know.

**Comment by nocarryr** [comment]
Yeah, I plan to add that, but...
I just now was able to make it work with my android device communicating with my dev computer!
Using [python-for-android](https://github.com/kivy/python-for-android) and just a basic test that shows the output from:
```python
client.center_freq = 2e6
print(client.center_freq)  #not really a print. adding text to a widget
samples = client.read_samples()
print(len(samples))
```
It worked!
:+1:

**Comment by chibill** [comment]
Cool!

**Comment by nocarryr** [comment]
[Here's a gist](https://gist.github.com/nocarryr/73d57c41eb25703b0f9b809d2bd7bd05) with pretty much all of the steps I used (not counting a few hours of figuring out the build config and debugging)

**Comment by chibill** [comment]
Question do you know if your bandwidth branch on your repo still works?

**Comment by nocarryr** [comment]
@chibill I'm not sure. I abandoned the idea when I realized that tuner bandwidth wasn't supported by many devices.
I recently discovered that there is an [active fork of librtlsdr](https://github.com/librtlsdr/librtlsdr/tree/development) that has the api support for the `getter` as of [this PR](https://github.com/librtlsdr/librtlsdr/pull/1), so it may be worth revisiting.
I don't have an R820T though, so I'd have no way to test it.

**Comment by chibill** [comment]
I can test it on R820T as I own two. (One older version that is long like a normal u.s. and another that is a small 1 inch square.)

**Comment by chibill** [comment]
I can confirm that your other branch with the bandwidth works on both of my rtl-sdr sdrs. (Requires the latest librtlsdr.)

**Comment by nocarryr** [comment]
Cool!  I may sync up that branch and see if I can add the other functionality at some point.

As for this PR though, I know there's still some clean-up to do and maybe some more documentation.

I'd really like to have @roger- chime in and give his thoughts just to be sure it's headed in a good direction.

**Comment by chibill** [comment]
Also for the latest binaries for Windows. https://github.com/librtlsdr/librtlsdr

**Comment by roger-** [comment]
This looks good to me, I'll have to play with it some more.

If Python 2 compatibility wasn't an issue it would have been nice to use async for all the TCP stuff.

**Comment by nocarryr** [comment]
Async is definitely something worth looking into. Could probably be done in py2 with external libs. 
That would probably be better in another PR though.
Are you alright with the way things are being done in __init__.py?

**Comment by roger-** [comment]
Ideally I  think the TCP code should be independent of the rest of the code base but this works  for now.

**Comment by chibill** [comment]
Any progress on getting this merged?

**Comment by nocarryr** [comment]
Sorry!  Got busy with work and a bit sidetracked.  I'll finish tidying things up so it can be merged

**Comment by nocarryr** [comment]
Closes #44

**Pull request merged**
