### PR TITLE
Use universal distribution

### PR DESCRIPTION
**Pull request by nocarryr**
* Keywords and syntax added in newer python versions are tested for and not used unless available
* The new language features from
  
  [PEP 492][pep492]: `async def foo(): pass`
  
  and [PEP 448][pep448]: `def bar(a,b, *, c): pass`
  
  are tested for their existence by the `exec` function, raising a `SyntaxError` if unavailable
* Implementations of those features will by default be triple-quoted strings unless they are supported by the interpreter.  If supported, they will be executed as code objects using the `exec` function.

This allows for all currently used versions of python (2.7, 3.x) to use the exact same source and binary (wheel) distribution and reduces many of the version checks otherwise needed throughout the project.

[pep492]:https://www.python.org/dev/peps/pep-0492
[pep448]:https://www.python.org/dev/peps/pep-0448

### CODE REVIEW

**Comment by nocarryr** [comment]
@roger- I realize this makes editing the `rtlsdraio` module a bit cumbersome, but I think the packaging and backwards-compatibility benefits are much more important.  We can work on making things a bit more elegant in the future.

**Comment by roger-** [comment]
Interesting approach, but would it be possible to do the `exec`  where rtlsdraio is imported instead of modifying rtlsdraio.py?

Really wish I had just kept the Py3k port on another branch!

**Comment by nocarryr** [comment]
I really wanted to do that, but it would have required a method injection after the class definition.  It seemed a bit more of a hack than it already was.  Oddly, the python stdlib's collections module uses a [similar approach](https://hg.python.org/cpython/file/3.5/Lib/collections/__init__.py#l300) and I've seen it done elsewhere.

If you have any ideas on how to implement that without method injection or subclassing, I'd like to hear them for sure

**Comment by roger-** [comment]
I'm okay with this for now :)

**Comment by nocarryr** [comment]
Ok.  I was trying to find a clean solution to the ongoing issue as it seems it hasn't gone away (issue #42)

Btw, the coverage decrease was because the CI build for py2.7 didn't upload its coverage data.  I can't retrigger the build because it's on your account, but you can if you want [here](https://travis-ci.org/roger-/pyrtlsdr/jobs/126908257)


Also, good to see you around!

**Pull request merged**
