### PR TITLE
Avoid importing rtlsdraio in PY2

### LINKED ISSUE #30: Importing rtlsdraio.py in PY2 causes syntax errors
The changes to method/function syntax in PY3 cause errors on import in PY2:
https://github.com/roger-/pyrtlsdr/blob/master/rtlsdr/rtlsdraio.py#L15

### PR DESCRIPTION
**Pull request by nocarryr**
Fixes #30

### CODE REVIEW

**Comment by roger-** [comment]
Thanks, might need to do something similar but it would still fail under Python 3.0 - 3.4.

**Comment by nocarryr** [comment]
Yup, I realized that shortly after submitting the PR.  Working on it now.

**Comment by nocarryr** [comment]
@roger- see if that is a fair enough solution.  I can take a different approach if necessary, but that seems to work on my machine.

**Comment by roger-** [comment]
That seems like it should work, thanks!

BTW did you try `except (ImportError, SyntaxError): pass`?

**Comment by nocarryr** [comment]
> BTW did you `try except (ImportError, SyntaxError): pass`?

I didn't think of that actually.  Would be more graceful, but I don't know about catching every `SyntaxError` on module level import.  May possibly lead to confusion with debugging things down the road, but I guess that's what syntax highlighters are for.

**Comment by roger-** [comment]
Ah, looks like you can't actually catch `SyntaxError` (outside of `eval()`).

Appreciate the fix!

**Comment by nocarryr** [comment]
No problem.  Now I need to find a box I can put py3.5 on!

**Pull request merged**
